/* spec-data.js — shared by deck.config.js and spec.html. Edit spec text here only.
 * Apple / Samsung values：面積比例引用 2026-09-23 拆解；像素值為本版 1920px CSS px、1× 截圖實測（Apple apple-ai.png、Samsung v1 截圖）。
 * Acer L1 values: 本提案建議值。 */
(() => {
  const NONE = { goal: '—', material: '—', ratio: '—', scope: '—', asset: '—', story: '—', none: true };
  window.SPEC = {
    dims: [['goal', '目標'], ['material', '素材'], ['ratio', '比例'], ['scope', '範圍'], ['asset', '資產'], ['story', '敘事']],

    bench: {
      apple: [
        { seg: 'Hero', goal: '立 Siri 為整頁入口', material: '可讀 UI 截圖拼貼（5 張）', ratio: '首屏圖片 29%；UI 字級 ≈13px；標題置中',
          scope: '1 句主標＋限制條件緊貼主標', asset: '中央 iPhone Siri 指令 UI ×1＋周邊介面 ×4', story: '宣言型主標；第一人稱「這是你的螢幕」' },
        { seg: '助理', goal: '讓讀者記住一句能對 Siri 說的話', material: 'UI 操作介面與精美視覺大圖：每張卡帶一句真實指令；精選卡有影片', ratio: '直式卡 0.83:1（372×450）；圓角 ≈24px；間距 20px；露出第 4 張',
          scope: 'Siri 章輪播 4+ 張，前接精選卡', asset: '每張 = 指令句＋結果截圖', story: '情境小標（Siri AI）＋一句獨立主標' },
        { seg: '情境功能', goal: '用章節標題證明覆蓋面', material: 'UI 操作介面與精美視覺大圖', ratio: '同一模板 ×4 章；≈330px／功能',
          scope: '視覺智慧／照片／溝通／生產力，各 4–5 張；次要功能降為 4 項 icon', asset: '19 張 UI 操作介面與視覺大圖', story: '每章情境小標＋獨立主標，附「使用可能會有所限制」' },
        { seg: '選機', goal: '依裝置類別選機', material: '去背裝置照', ratio: '4 分頁；主 CTA「進一步了解」，購買為次要文字連結',
          scope: 'iPhone／iPad／筆電／桌機', asset: '每分頁去背照 ×3', story: '「體驗 Apple Intelligence 的實力」' },
        { seg: '相容清單', goal: '用晶片回答「我的裝置能不能用」', material: '純文字清單', ratio: '三欄文字；每列可點',
          scope: '約 30 個機型', asset: '機型＋晶片括號清單', story: '晶片名稱成為選機依據（A18 Pro、M1 以上）' },
        { ...NONE, seg: 'FAQ' },
      ],
      samsung: [
        { seg: 'Hero', goal: '建立 Galaxy AI 品牌印象', material: '棚拍手持商品', ratio: '滿版 1920×1080（1.78:1）；首屏圖片 62%；標題置中',
          scope: '1 句標語＋AI companion 定位', asset: '產品 KV ×1', story: '定義型標語「Make life more seamless」；廣告語氣' },
        { seg: '助理', goal: '把功能收束成單一入口，埋第一個導購 CTA', material: 'Bixby 對話 UI 截圖', ratio: '單段；左文右圖',
          scope: '1 段＋中段 CTA', asset: '對話 UI ×1', story: 'AI companion，人格化定位' },
        { seg: '情境功能', goal: '一屏感受 AI 覆蓋一整天', material: '沉浸感的情境照結合 UI', ratio: '橫式卡 1.36:1（856×631）；圓角 ≈24px；間距 94px；圖片占比 35–47%',
          scope: '5 分頁 × 14 功能，預設露出 2 張', asset: '14 張情境照合成 UI', story: '提問式「Can your phone do that?」；第三人稱使用瞬間' },
        { seg: '選機', goal: '依裝置類別選機', material: '去背商品照', ratio: '4 分頁；前接 Try Galaxy 轉場',
          scope: '手機／平板／手錶／耳機', asset: '去背商品攝影', story: '「Explore our range of Galaxy AI devices」＋Learn more' },
        { ...NONE, seg: '相容清單' },
        { seg: 'FAQ', goal: '集中免責與長尾 SEO', material: '文字手風琴', ratio: 'FAQ＋19 條註腳，頁尾前最長的文字段',
          scope: '9–11 題＋19 條註腳', asset: 'FAQ 文案＋註腳', story: '用讀者會問的句子當題目' },
      ],
    },

    l1: [
      { id: 'L1-1', seg: 'Hero：Acer Qubi 全新亮相!', ref: { page: 'apple', region: 'hero', label: 'Apple · Siri Hero（白底）' },
        goal: '一眼知道「AI 助理 Qubi 就在你的電腦裡」，並往下讀',
        material: 'A 版：綠色 Qubi 字樣＋Qubi 3D 角色；B 版：筆電正面產品圖＋Qubi 3D 角色',
        ratio: '全白底 16:9。A 版：Qubi 字樣置中，縮成主標後 Qubi 置中、主標與副標在下；B 版：主標與副標靠左，筆電在右，Qubi 在螢幕內',
        scope: '1 句主標（Acer Qubi 全新亮相!）＋1 句副標；不放 CTA 與限制說明（移到 FAQ 註腳）',
        asset: 'Qubi 3D 角色動畫（A 版約 7 秒、B 版約 5 秒）；B 版另需筆電正面去背圖（透明底 PNG @2x）',
        story: 'A 版：Qubi 從 Q 的窗框探頭、跳出揮手，字樣縮成「Acer Qubi 全新亮相!」；B 版：Qubi 從筆電螢幕內探頭揮手。兩版都在說 AI 助理就在你的電腦裡' },
      { id: 'L1-2', seg: 'Qubi 章：對話＋情境輪播', ref: { page: 'apple', region: 'siri', label: 'Apple · Siri 章（位置）' },
        goal: '讓讀者看到 Qubi 能做的事：問什麼，就換什麼場景',
        material: '3:2 情境照卡片輪播，對話框疊在卡片上',
        ratio: '淺灰底 2:1；置中卡 720×480、兩側卡縮小 72% 並淡化；對話出現時底圖壓暗；標題置中，與 03 一致',
        scope: '小標 Acer Qubi＋1 句主標；3 組對話（郵件摘要・人物去背・會議摘要），約 5 秒一組；不放 CTA',
        asset: '情境照 3 張（3:2，1440×960 @2x）；對話腳本 3 組；人物去背加裁切框與掃描線動態',
        story: '主標「個人 AI 助理，Qubi 比你更懂你」；Qubi 主動提議，也接受使用者拖檔案提問' },
      { id: 'L1-3', seg: '情境功能', ref: { page: 'samsung', region: 'scenario', label: 'Samsung · 情境分頁' },
        goal: '一屏感受「AI 覆蓋我一整天」',
        material: '沉浸感的情境照結合 UI，一張圖 = 一個使用時刻',
        ratio: '橫式卡 1.36:1；圓角 ≈3% 卡寬；間距一致；圖片占比 35–47%；≤200px／功能',
        scope: '4 分頁（商務／創意／遊戲／個人化）× 7–9 個 AIS app',
        asset: '每個 app 情境照合成 UI ×1，1712×1262 @2x；v1 圖可沿用或改版',
        story: '置中小標＋置中大標（把 Samsung「Can your phone do that?」改寫成肯定句），與 02 一致；卡片 = 功能標題＋2–3 行說明' },
      { id: 'L1-4', seg: '選機：依裝置類別', ref: { page: 'samsung', region: 'selling', label: 'Samsung · 機種探索' },
        goal: '從「想用的功能」導到 acer.com 裝置分類頁；已有 Acer 電腦 → 下載',
        material: '去背商品照',
        ratio: '4 分頁 × 3 張系列卡；約占內容 20%',
        scope: '筆電／桌機／AIO／掌機；每卡 = 一個系列；主 CTA「進一步了解」→ 分類頁，次 CTA「下載 Acer Intelligence Space」',
        asset: '系列去背照約 12 張（官網現有）＋系列名與一句定位',
        story: '標題承接軟體→硬體：「哪一台跑得動你的 AI？」' },
      { id: 'L1-5', seg: 'FAQ', ref: { page: 'samsung', region: 'faq', label: 'Samsung · FAQ' },
        goal: '集中處理免責與長尾問題，兼顧 SEO',
        material: '文字手風琴',
        ratio: '單欄；預設收合',
        scope: '5–8 題：支援機型（取代相容清單）、語言、下載與費用、Qubi 是什麼、資料怎麼處理',
        asset: 'FAQ 文案＋註腳',
        story: '用讀者會問的句子當題目' },
    ],

    overview: [
      { dim: '目標', apple: '介紹整套 AI 系統，最後用相容清單綁回晶片與機型', samsung: '用情境推動硬體探索', acer: '認識 AIS＋Qubi，依裝置類別導到分類頁' },
      { dim: '素材', apple: 'UI 操作介面與精美視覺大圖（圖片中 92% 為可讀介面）', samsung: '沉浸感的情境照結合 UI＋去背商品照', acer: '白底產品＋Qubi 動畫（Hero）＋情境照卡片（Qubi 章）＋生活照合成 UI（情境）＋去背照（選機）' },
      { dim: '比例', apple: '首屏圖片 29%；卡片 0.83:1、圓角 ≈24px', samsung: '首屏圖片 62%；卡片 1.36:1、圓角 ≈24px', acer: 'Hero 全白底 16:9、Qubi 章 2:1（卡片 3:2）、情境卡 1.36:1；內容約 4,400px，含導覽與頁尾約 5,600px' },
      { dim: '範圍', apple: '6 章約 30 個功能；4 類裝置；約 30 個機型', samsung: '5 分頁 14 個功能；4 類裝置', acer: 'Qubi 章 3 組對話；4 分頁 × 7–9 app；4 類裝置 × 3 系列' },
      { dim: '資產', apple: '36 張 UI／情境圖＋2 支影片＋15 張商品去背', samsung: '18 張情境照／KV＋11 張商品去背，無影片', acer: 'Qubi 3D 動畫 1、筆電去背圖 1（B 版）、Qubi 章情境照 3、情境圖 7–9、系列去背照約 12' },
      { dim: '敘事', apple: '角色（Siri）開場；「這是你的螢幕」', samsung: '提問開場；「它出現在你生活的某個時刻」', acer: 'Qubi 開場＋「你的電腦也做得到」情境＋「哪一台跑得動你的 AI？」' },
    ],

    // L1 wireframe, page px at 1440 wide; y is relative to each segment. k: line | block | card | asset | cta | tab.
    // a = asset number (must exist in assets); quiet = draw the box without repeating its chip.
    wireframe: {
      width: 1440,
      segments: [
        { id: 'L1-1', h: 810, boxes: [
          // A 版的最後畫面：Qubi 置中，主標（由 Qubi 字樣縮成）與副標在下；B 版的筆電（A02）不在此版面
          { k: 'asset', a: 'A01', x: 630, y: 250, w: 180, h: 260 },
          { k: 'line', x: 400, y: 560, w: 640, h: 80, t: 'Acer Qubi 全新亮相!（主標）' },
          { k: 'line', x: 360, y: 672, w: 720, h: 26, t: '副標' },
        ] },
        { id: 'L1-2', h: 720, boxes: [
          { k: 'line', x: 630, y: 38, w: 180, h: 24, t: 'Acer Qubi' },
          { k: 'line', x: 400, y: 70, w: 640, h: 48, t: '主標' },
          { k: 'asset', a: 'A03', x: 0, y: 243, w: 279, h: 346, quiet: true },
          { k: 'asset', a: 'A03', x: 1161, y: 243, w: 279, h: 346, quiet: true },
          { k: 'asset', a: 'A03', x: 360, y: 176, w: 720, h: 480 },
          { k: 'asset', a: 'A04', x: 450, y: 330, w: 540, h: 112 },
        ] },
        { id: 'L1-3', h: 1000, boxes: [
          { k: 'line', x: 620, y: 52, w: 200, h: 28, t: '情境', fill: 'AI 應用' },
          { k: 'line', x: 360, y: 92, w: 720, h: 56, t: '大標', fill: '你的電腦也做得到' },
          { k: 'tab', x: 430, y: 180, w: 130, h: 42, t: '商務' },
          { k: 'tab', x: 575, y: 180, w: 130, h: 42, t: '創意' },
          { k: 'tab', x: 720, y: 180, w: 130, h: 42, t: '遊戲' },
          { k: 'tab', x: 865, y: 180, w: 130, h: 42, t: '個人化' },
          { k: 'asset', a: 'A05', x: 142, y: 280, w: 560, h: 412 },
          { k: 'asset', a: 'A05', x: 738, y: 280, w: 560, h: 412, quiet: true },
          { k: 'line', x: 142, y: 724, w: 520, h: 32, t: '功能標題', fill: '會議一結束，重點已整理好' },
          { k: 'line', x: 142, y: 772, w: 520, h: 24, fill: 'Meeting Assistant 自動產生逐字稿與摘要' },
                    { k: 'line', x: 738, y: 724, w: 520, h: 32, t: '功能標題', fill: '一句話生成簡報配圖' },
          { k: 'line', x: 738, y: 772, w: 520, h: 24, fill: 'AI Drawing 依描述產生插圖' },
                  ] },
        { id: 'L1-4', h: 900, boxes: [
          { k: 'line', x: 360, y: 88, w: 720, h: 56, t: '哪一台跑得動你的 AI？', fill: '哪一台跑得動你的 AI？' },
          { k: 'tab', x: 430, y: 180, w: 130, h: 42, t: '筆電' },
          { k: 'tab', x: 575, y: 180, w: 130, h: 42, t: '桌機' },
          { k: 'tab', x: 720, y: 180, w: 130, h: 42, t: 'AIO' },
          { k: 'tab', x: 865, y: 180, w: 130, h: 42, t: '掌機' },
          { k: 'card', x: 142, y: 280, w: 370, h: 470 },
          { k: 'card', x: 535, y: 280, w: 370, h: 470 },
          { k: 'card', x: 928, y: 280, w: 370, h: 470 },
          { k: 'asset', a: 'A06', x: 187, y: 310, w: 280, h: 220 },
          { k: 'asset', a: 'A06', x: 580, y: 310, w: 280, h: 220, quiet: true },
          { k: 'asset', a: 'A06', x: 973, y: 310, w: 280, h: 220, quiet: true },
          { k: 'line', x: 172, y: 556, w: 310, h: 30, t: '系列名', fill: 'Swift Go 14' },
          { k: 'line', x: 565, y: 556, w: 310, h: 30, left: true, t: '系列名', fill: 'Predator Helios Neo 16S' },
          { k: 'line', x: 958, y: 556, w: 310, h: 30, t: '系列名', fill: 'Aspire Lite 14' },
          { k: 'line', x: 172, y: 600, w: 310, h: 24, fill: '輕薄續航，AI 隨身帶著走' },
          { k: 'line', x: 565, y: 600, w: 310, h: 24, left: true, fill: '遊戲與創作，本地 AI 全速跑' },
          { k: 'line', x: 958, y: 600, w: 310, h: 24, fill: '入門首選，日常 AI 就夠用' },
          { k: 'cta', x: 172, y: 670, w: 210, h: 46, t: '進一步了解', primary: true },
          { k: 'cta', x: 565, y: 670, w: 210, h: 46, t: '進一步了解', primary: true },
          { k: 'cta', x: 958, y: 670, w: 210, h: 46, t: '進一步了解', primary: true },
          { k: 'cta', x: 620, y: 820, w: 200, h: 52, t: '下載 AIS' },
        ] },
        { id: 'L1-5', h: 950, boxes: [
          { k: 'line', x: 420, y: 86, w: 600, h: 52, t: '常見問題', fill: '常見問題' },
          { k: 'asset', a: 'A07', x: 270, y: 170, w: 900, h: 590 },
          { k: 'block', x: 300, y: 260, w: 840, h: 60, t: '問題 1　＋', fill: '哪些 Acer 電腦可以使用 Acer Intelligence Space？　＋' },
          { k: 'block', x: 300, y: 340, w: 840, h: 60, t: '問題 2　＋', fill: 'Qubi 是什麼？需要付費嗎？　＋' },
          { k: 'block', x: 300, y: 420, w: 840, h: 60, t: '問題 3　＋', fill: '支援哪些語言？　＋' },
          { k: 'block', x: 300, y: 500, w: 840, h: 60, t: '問題 4　＋', fill: '我的資料會被上傳到雲端嗎？　＋' },
          { k: 'block', x: 300, y: 580, w: 840, h: 60, t: '問題 5　＋', fill: '如何下載與更新？　＋' },
          { k: 'line', x: 270, y: 810, w: 700, h: 12 },
          { k: 'line', x: 270, y: 834, w: 620, h: 12 },
        ] },
      ],
    },

    // benchmark pages section by section: copy and image files (read from the live pages)
    benchAssets: {
      date: '2026-09-24',
      apple: { name: 'Apple Intelligence', url: 'apple.com/tw/apple-intelligence',
        conclusion: '1. 以 Siri 開場進入敘事　　2. 用多影像凸顯強大品牌力',
        totals: [['Image', 36], ['商品去背', 15], ['Video', 2], ['Icon', 6]],
        rows: [
          { cat: 'brand', seg: 'Hero', title: '全新 Siri AI 亮相。真能幫助你，真的很懂你。', sub: '眉標：Apple Intelligence 與 Siri', assets: 'Image ×6（iPhone＋UI 拼貼）' },
          { cat: 'feature', seg: '精選', title: '探索 Apple Intelligence 的全新特點', sub: '6 張精選卡：Siri AI・視覺智慧・照片編輯・自然對談・隨處寫作・常用 App', assets: 'Image ×4＋Video ×2' },
          { cat: 'feature', seg: 'Siri AI', title: '你的 AI 助理，更個人化，更強大。', sub: '儘管開口問 Siri／了解你的個人情況／在更多 App 中操作／世界知識／Siri App／說話方式／CarPlay', assets: 'Image ×7（UI 操作介面）' },
          { cat: 'feature', seg: '視覺智慧', title: '視覺智慧', sub: '相機 App 上的 Siri 模式／智慧建議操作／眼前一切都可問 Siri／Mac・iPad・Vision Pro', assets: 'Image ×5（UI 操作介面）' },
          { cat: 'feature', seg: '照片與影像', title: '照片與影像', sub: '智慧照片編輯／重新構圖／影像樂園／影像魔杖', assets: 'Image ×4（照片＋UI）' },
          { cat: 'feature', seg: '溝通交流', title: '溝通交流', sub: '隨處用 Siri 寫作／主動給建議／校對／通話資訊／即時翻譯', assets: 'Image ×5（UI 操作介面）' },
          { cat: 'feature', seg: '生產力', title: '生產力', sub: 'Safari 更聰明／密碼／建立捷徑／聽寫／描述行事曆行程', assets: 'Image ×5（UI 操作介面）' },
          { cat: 'feature', seg: '更多精彩', title: 'Apple Intelligence 與 Siri AI 功能還有更多精彩', sub: '輔助使用／家，更加智慧／Genmoji／Workout Buddy', assets: 'Icon ×4' },
          { cat: 'security', seg: '隱私', title: '優異的隱私保護，隨優越實力而來。', sub: '私密雲端運算', assets: 'Icon ×1' },
          { cat: 'hardware', seg: '選機', title: '體驗 Apple Intelligence 的實力', sub: 'iPhone 6 款・iPad 3 款・Mac 6 款，分頁切換', assets: '商品去背 ×15' },
          { cat: 'hardware', seg: '相容裝置', title: '與 Apple Intelligence 相容的裝置', sub: '文字清單，機型後附晶片', assets: '—（純文字）' },
          { cat: 'brand', seg: 'SDK', title: '為常用 App，帶來更多新可能。', sub: '開發者 SDK', assets: 'Icon ×1' },
        ] },
      samsung: { name: 'Samsung Galaxy AI', url: 'samsung.com/us/galaxy-ai',
        conclusion: '1. 以情境提問進入敘事　　2. 用沉浸式影像代入使用者日常',
        totals: [['Image', 18], ['商品去背', 11], ['Video', 0], ['Icon', 0]],
        rows: [
          { cat: 'brand', seg: 'Hero', title: 'Galaxy AI. Make life more seamless.', sub: '手持折疊機主視覺', assets: 'Image ×1（KV）' },
          { cat: 'feature', seg: '功能', title: 'Can your phone do that?', sub: '5 分頁 Personalization・Creativity・Communication・Productivity・Health，14 則功能標題', assets: 'Image ×14（沉浸感的情境照結合 UI）' },
          { cat: 'feature', seg: 'Bixby', title: 'Smart assistance that&#39;s always available', sub: '對話 UI＋中段 CTA', assets: 'Image ×1（UI 實拍）' },
          { cat: 'security', seg: '資安', title: 'How Galaxy AI keeps your data secure', sub: 'Digital fortress／Privacy settings／Trust across your Galaxy', assets: 'Image ×1（Knox 圖像）' },
          { cat: 'hardware', seg: '試用', title: 'Try Galaxy', sub: '非 Galaxy 用戶也能先試用', assets: 'Image ×1（橫幅）' },
          { cat: 'hardware', seg: '選機', title: 'Explore our range of Galaxy AI devices', sub: 'Smartphones・Tablets・Watches・Buds 4 分頁', assets: '商品去背 ×11' },
          { cat: 'seo', seg: 'FAQ', title: 'Frequently Asked Questions', sub: '11 題，例：What devices have Galaxy AI?', assets: '—（純文字）' },
        ] },
    },

    // Acer L1, section by section: suggested copy (draft) and image assets, for the summary sheet
    acerSheet: { name: 'Acer', conclusion: '開場的敘事框架參考 Apple，其餘細節與影像素材參考 Samsung', src: 'Milestone 1 landing page 建議・文案為草稿',
      totals: [['Image', '10–12'], ['商品去背', '約 13'], ['動畫', 1], ['Icon', 0]],
      rows: [
        { ref: 'Apple', seg: 'Hero', title: 'Acer Qubi 全新亮相!', sub: '副標：新一代 Acer Intelligence Space 與 Acer Qubi 就在你的電腦裡，幫你做得更多、更懂你。', assets: 'A01 Qubi 3D 動畫（B 版＋A02 筆電圖）' },
        { ref: 'Apple', seg: 'Qubi 章', title: '個人 AI 助理，Qubi 比你更懂你', sub: '小標 Acer Qubi；對話：郵件摘要・人物去背・會議摘要', assets: 'A03 情境照 ×3＋A04 腳本 ×3' },
        { ref: 'Samsung', seg: '情境功能', title: '你的電腦也做得到', sub: '分頁：商務・創意・遊戲・個人化；7–9 則功能標題', assets: 'A05 情境圖 ×7–9' },
        { ref: 'Samsung', seg: '選機', title: '哪一台跑得動你的 AI？', sub: '筆電・桌機・AIO・掌機；CTA 進一步了解・下載 AIS', assets: 'A06 系列去背照 ×約 12' },
        { ref: 'Samsung', seg: 'FAQ', title: '常見問題', sub: '5–8 題，含支援機型、語言、費用、資料處理', assets: 'A07 FAQ 文案（純文字）' },
      ] },

    // copy table: every L1 section item by item, next to the reference brand's copy (Hero / Qubi → Apple, the rest → Samsung).
    // Reference copy read from the live pages on 2026-09-26 (Samsung footnote markers removed, long descriptions trimmed);
    // Acer copy is a draft (scenario cards from the v1 mockup). Cells may hold html (<b>, <i>, <br>).
    copyTable: [{"seg":"Hero","ref":"Apple","assets":["Image ×6（iPhone＋UI 拼貼）","A01 Qubi 3D 動畫（A、B 版）＋A02 筆電去背圖（B 版）"],"rows":[["眉標","Apple Intelligence 與 Siri","Acer Intelligence Space"],
        ["主標","全新 Siri AI 亮相。真能幫助你，真的很懂你。","Acer Qubi 全新亮相"],
        ["內文","新一代 Apple Intelligence 與 Siri 聯手亮相，帶來真能幫助你的 AI，一切以你和你的需求為核心。","新一代 Acer Intelligence Space 與 Acer Qubi 就在你的電腦裡，幫你做得更多、更懂你。"]]},
      {"seg":"Qubi 章","ref":"Apple","assets":["Image ×7（UI 操作介面）＋Video ×2","A03 情境照 ×3＋A04 對話腳本 ×3"],"rows":[["眉標","Siri AI","Acer Qubi"],
        ["主標","你的 AI 助理，更個人化，更強大。","個人 AI 助理，Qubi 比你更懂你"],
        ["內文","Siri AI 由 Apple Intelligence 驅動，透過更深入的回答、自然流暢的對話，以及全新的專屬 app，助你完成更多事。","Acer Qubi 看得懂你正在做的事，主動提出下一步，直接調動 Acer Intelligence Space 內符合需求的助理，一句話就完成。"],
        ["卡片 / 對話 #1","儘管開口問 Siri。","Qubi：要幫你做郵件摘要嗎？"],
        ["卡片 / 對話 #2","Siri 了解你的個人情況。","你：可以幫我把人物去背嗎？"],
        ["卡片 / 對話 #3","在更多 App 中進行操作。","Qubi：要幫你做會議摘要嗎？"]]},
      {"seg":"情境功能","ref":"Samsung","assets":["Image ×2","A05 情境圖 ×3"],"rows":[["主標","Can your phone do that?","你的電腦也做得到"],["內文","Galaxy AI offers a wide variety of already-available features that you can jump right into.","從會議到創作，讓它為你多做一點。"],["情境 #1","<b class=\"tab\">Productivity</b>","<b class=\"tab\">商務｜掌握對話，推進工作。</b>"],["1","<b>Get clean scans in a snap</b><i>Document Scan</i><br>Document Scan can detect documents and lets you capture them with your phone, and then it can clean them up for you by removing unwanted distortions, corner folds, stray fingers and more. Perfect for receipts or forms, and way faster than running to the scanner.","<b>聽的同時，也能看見對話。</b><i>即時字幕</i><br>參與多語言會議時，透過即時字幕輔助掌握對話。想確認剛才的一句，也能查看字幕歷史，接著參與討論。"],["2","<b>Written and formatted your way</b><i>Writing Assist</i><br>Writing Assist is a handy editor on your Galaxy phone or tablet. Take any written or selected text on your device and have Writing Assist proofread it, reformat it, tweak the wording or summarize everything into key points.","<b>專心談，重點留著回頭看。</b><i>會議逐字稿與摘要</i><br>討論時，把注意力留給溝通與提問。會後透過逐字稿與摘要回顧內容，整理下一步需要確認的事。"],["3","—","<b>接手新專案，從一個問題開始。</b><i>本機文件問答</i><br>面對不熟悉的專案文件，先問你想了解的事。透過本機文件問答掌握內容，再進一步查閱與確認。"]]},
      {"seg":"情境功能","ref":"Samsung","assets":["Image ×5","A05 情境圖 ×3"],"rows":[["情境 #2","<b class=\"tab\">Creativity</b>","<b class=\"tab\">創意｜把腦中的畫面，快速變成作品。</b>"],["1","<b>Refine your framing without reshooting</b><i>My FanCam</i><br>Change your wide-angle video into a subject-centered tracking shot cropped to your choice of aspect ratio — putting the spotlight on someone in the crowd.","<b>隨手一張草圖，就能生成完整作品。</b><i>草圖生圖</i><br>把手繪草圖交給 AI，快速生成細節豐富的圖片，保留你原本的構圖與想法。"],["2","<b>Make your picture perfect in seconds</b><i>Photo Assist</i><br>Move, resize or delete objects by hand and have AI fill in the gaps for a seamless look. You can also enter a prompt or reference image to add new elements into the image, like putting a hat on a subject.","<b>同一個畫面，換個風格再看看。</b><i>風格轉換</i><br>素描、水墨、幾何一鍵轉換，多試幾種風格，找到最適合作品的樣子。"],["3","<b>Design your feed with Creative Studio</b><i>Creative Studio</i><br>Create your own personalized designs for greeting cards, wallpapers and more by combining text with drawings or images. Generate sticker sets in the styles and concepts you want.","<b>忘了檔名，描述畫面就找得到。</b><i>本機素材搜尋</i><br>記得照片裡有雪山和湖，卻想不起檔名？用一句描述搜尋本機素材，馬上找到。"],["4","<b>Filter out the noise and crank up the vibes</b><i>Audio Eraser</i><br>Audio Eraser removes background noise from videos to clean up audio in just a couple of taps, from concerts you have attended to travel videos filmed on the go.","—"],["5","<b>Instantly compile your best moments</b><i>Auto Trim</i><br>Auto Trim extracts key moments in your videos to create a clip of highlights centered around a specific activity — beautifully edited videos without the work of actual editing.","—"]]},
      {"seg":"情境功能","ref":"Samsung","assets":["Image ×3","A05 情境圖 ×3"],"rows":[["情境 #3","<b class=\"tab\">Communication</b>","<b class=\"tab\">遊戲｜看得更清楚，打得更準。</b>"],["1","<b>Let AI handle unwanted calls for you</b><i>Call Screening</i><br>Call Screening filters calls from unknown numbers and displays a quick text preview of why they are calling, so you can decide whether to pick up or not. For spam and scams, it can just end the call for you.","<b>準星自動變色，暗處也看得見。</b><i>智慧準星</i><br>依照遊戲畫面自動調整準星顏色，不管場景明暗，目標都能清楚鎖定。"],["2","<b>Turn long recordings into short summaries</b><i>Transcript Assist</i><br>Transcript Assist converts your recordings into text, then lets you summarize or translate them with a tap. Review complex conversations with ease, or take lecture notes by recording your class and tapping Summarize.","<b>遠方細節放大看，夜裡也清楚。</b><i>放大與夜視</i><br>放大與夜視輔助讓遠處敵人和陰暗角落一目了然，搶先一步做出反應。"],["3","<b>Don&#39;t let language be a barrier</b><i>Interpreter</i><br>With a long press on your Galaxy Buds, Interpreter can translate speech in real time for smooth listening in your own language, with the translated text displayed on your Galaxy phone.","<b>精彩時刻自動剪好，馬上分享。</b><i>精彩片段</i><br>AI 自動擷取擊殺與關鍵片段，時間軸上直接挑選剪輯，打完就能分享。"]]},
      {"seg":"情境功能","ref":"Samsung","assets":["Image ×2","A05 情境圖 ×2"],"rows":[["情境 #4","<b class=\"tab\">Personalization</b>","<b class=\"tab\">個人化｜讓電腦更懂你的日常。</b>"],["1","<b>A little nudge to your next action keeps you focused</b><i>Now Nudge</i><br>Now Nudge recognizes what is happening on your screen and provides relevant suggestions based on the context — like prompts to view the Calendar app while you are making plans with a friend via text.","<b>回信不卡關，語氣一鍵調整。</b><i>郵件語氣改寫</i><br>收到邀請不知道怎麼回？選好想要的語氣，AI 幫你寫好草稿，改一改就能送出。"],["2","<b>Get personalized insights tailored to you</b><i>Now Brief</i><br>Customize Now Brief by writing prompts for briefings you would like to receive based on your interests. Action buttons help you stay connected, like requesting a ride to plans saved in your calendar.","<b>信件自動分類，重要的先看。</b><i>郵件分類</i><br>購物通知、訂閱內容、日常往來自動整理，打開信箱就知道該先處理哪一封。"]]},
      {"seg":"選機","ref":"Samsung","assets":["商品去背 ×11","A06 系列去背照 ×約 12"],"rows":[["主標","Explore our range of Galaxy AI devices","哪一台跑得動你的 AI？"],
        ["內文 / 分頁","Smartphones・Tablets・Watches・Buds","<ul><li>依裝置類別挑選適合你的 Acer AI PC</li><li>分頁：筆電・桌機・AIO・掌機</li></ul>"],
        ["卡片","Galaxy Z Fold8・Galaxy Z Fold8 Ultra・Galaxy S26 Ultra","<ul><li>Swift Go 14｜輕薄續航，AI 隨身帶著走</li><li>Predator Helios Neo 16S｜遊戲與創作，本地 AI 全速跑</li><li>Aspire Lite 14｜入門首選，日常 AI 就夠用</li></ul>"],
        ["CTA","Learn more","<ul><li>進一步了解（→ 分類頁）</li><li>下載 Acer Intelligence Space</li></ul>"]]},
      {"seg":"FAQ","ref":"Samsung","assets":["—（純文字）","A07 FAQ 文案（純文字）"],"rows":[["主標","Frequently Asked Questions","常見問題"],
        ["Q1","What devices have Galaxy AI?","哪些 Acer 電腦可以使用 Acer Intelligence Space？"],
        ["Q2","What languages does Galaxy AI support?","支援哪些語言？"],
        ["Q3","Is Galaxy AI secure in terms of privacy?","我的資料會被上傳到雲端嗎？"],
        ["Q4","How do I use Galaxy AI on my Samsung phone?","如何下載與更新？"],
        ["Q5","—","Qubi 是什麼？需要付費嗎？"]]}],

    // English draft of the Acer copy, one entry per copyTable group and row (same order); written as native copy,
    // not a literal translation. The spec appendix shows it as an extra column.
    copyTableEn: [
      { assets: 'A01 Qubi 3D animation (versions A and B) + A02 laptop cutout (version B)', rows: [
        'Acer Intelligence Space',
        'Meet Acer Qubi.',
        'The new Acer Intelligence Space and Acer Qubi live right on your PC, helping you get more done and getting to know you along the way.'] },
      { assets: 'A03 lifestyle photos ×3 + A04 chat scripts ×3', rows: [
        'Acer Qubi',
        'Your personal AI assistant. It knows what you need, sometimes before you do.',
        'Qubi sees what you&#39;re working on, suggests what to do next, and brings in the right assistant from Acer Intelligence Space. Just say the word.',
        'Qubi: Want me to summarize these emails?',
        'You: Can you remove the background from this photo?',
        'Qubi: Want a summary of this meeting?'] },
      { assets: 'A05 scenario images ×3', rows: [
        'Your PC can do that, too.',
        'From meetings to creative projects, let it take a little more off your plate.',
        '<b class="tab">Work | Stay on top of the conversation. Keep work moving.</b>',
        '<b>Follow every word as it&#39;s spoken.</b><i>Live Captions</i><br>Live captions help you keep up in multilingual meetings. Missed something? Scroll back through the caption history and jump right back in.',
        '<b>Stay in the conversation. Catch the details later.</b><i>Meeting Transcripts &amp; Summaries</i><br>Focus on the discussion while it&#39;s happening. Afterward, review the transcript and summary to line up your next steps.',
        '<b>New project? Start with a question.</b><i>On-device Document Q&amp;A</i><br>Facing unfamiliar project files? Ask what you need to know first, get the gist, then dig into the details.'] },
      { assets: 'A05 scenario images ×3', rows: [
        '<b class="tab">Create | Turn the picture in your head into finished work, fast.</b>',
        '<b>From rough sketch to finished artwork.</b><i>Sketch to Image</i><br>Hand your sketch to AI and get a richly detailed image in seconds, with your composition and ideas intact.',
        '<b>Same scene, new style.</b><i>Style Transfer</i><br>Switch between pencil, ink wash and geometric styles in one click. Try a few until one feels right.',
        '<b>Forgot the file name? Just describe the photo.</b><i>On-device Media Search</i><br>Remember the snowy peaks and the lake, but not the file name? Describe it in a sentence and find it on your PC instantly.',
        '—',
        '—'] },
      { assets: 'A05 scenario images ×3', rows: [
        '<b class="tab">Game | See more. Aim better.</b>',
        '<b>A crosshair that stands out, even in the dark.</b><i>Smart Crosshair</i><br>Your crosshair changes color to match the scene, so your target stays clear in bright light or deep shadow.',
        '<b>Spot distant details, even at night.</b><i>Zoom &amp; Night Vision</i><br>Zoom and night vision bring far-off enemies and dark corners into view, so you can react first.',
        '<b>Highlights, clipped and ready to share.</b><i>Highlights</i><br>AI captures your kills and key plays automatically. Pick your clips right from the timeline and share them as soon as the match ends.'] },
      { assets: 'A05 scenario images ×2', rows: [
        '<b class="tab">Personal | A PC that fits the way you live.</b>',
        '<b>Never get stuck on a reply. Set the tone in one click.</b><i>Email Tone Rewrite</i><br>Not sure how to answer an invite? Pick a tone, let AI draft the reply, tweak it and hit send.',
        '<b>A sorted inbox. What matters comes first.</b><i>Smart Email Sorting</i><br>Order updates, newsletters and everyday messages are organized for you, so you know what to open first.'] },
      { assets: 'A06 series cutouts ×~12', rows: [
        'Which Acer PC is ready for your AI?',
        '<ul><li>Find the right Acer AI PC for the way you work and play</li><li>Tabs: Laptops · Desktops · All-in-Ones · Handhelds</li></ul>',
        '<ul><li>Swift Go 14 | Thin, light and built to last all day, with AI wherever you go</li><li>Predator Helios Neo 16S | On-device AI at full speed for gaming and creating</li><li>Aspire Lite 14 | A great first AI PC, with everything you need for every day</li></ul>',
        '<ul><li>Learn more (→ category page)</li><li>Download Acer Intelligence Space</li></ul>'] },
      { assets: 'A07 FAQ copy (text only)', rows: [
        'Frequently asked questions',
        'Which Acer PCs support Acer Intelligence Space?',
        'Which languages are supported?',
        'Is my data uploaded to the cloud?',
        'How do I download and update it?',
        'What is Qubi, and is it free?'] },
    ],

    // framework page: which opening sections each brand uses, and the order of assistant vs scenarios
    framework: {
      apple: { take: 7, groups: [[0, 2, '角色：Siri 個人助理'], [3, 6, '情境章節']] },
      samsung: { take: 3, groups: [[0, 0, '品牌'], [1, 1, '情境分頁'], [2, 2, '助理：Bixby']] },
      conclusion: 'Acer 更適合 Apple 的敘事框架：從 Qubi（個人助理）出發，再帶到使用情境',
      diagram: {
        apple: { order: ['hero', 'assistant', 'context'], layout: 'vertical', note: '由人機介面帶動不同情境',
          copy: { hero: '「全新 Siri AI 亮相。真能幫助你，真的很懂你。」宣言型，角色先登場', assistant: '「你的 AI 助理，更個人化，更強大。」＋7 則小標，卡上是一句指令' }, contexts: ['視覺智慧', '照片與影像', '溝通交流', '生產力'] },
        samsung: { order: ['hero', 'context', 'assistant'], layout: 'horizontal', note: '不同情境背後都有一個人機介面',
          copy: { hero: '「Galaxy AI. Make life more seamless.」定義型品牌標語', assistant: '「Smart assistance that&#39;s always available」單段說明 Bixby' }, contexts: ['Personalization', 'Creativity', 'Communication', 'Productivity', 'Health'] },
      },
    },
    // assets page: one representative image per brand
    assetPick: {
      apple: { src: 'content/assets-pick/apple-siri-card.png', title: 'UI 操作介面與精美視覺大圖', points: ['介面清晰可讀，直接呈現真實指令', '大尺寸精緻視覺圖，彰顯 Apple 強大品牌力', '多格 UI 操作介面，彰顯軟硬體深度結合'],
        counts: [['Image', 36], ['商品去背', 15], ['Video', 2], ['Icon', 6]] },
      samsung: { src: 'content/assets-pick/samsung-now-brief.jpg', title: '沉浸感的情境照結合 UI', points: ['真實生活場景，UI 浮在畫面上', '一張圖描述一個沉浸式場景', '使用者容易代入日常生活裡'],
        counts: [['Image', 18], ['商品去背', 11], ['Video', 0], ['Icon', 0]] },
      conclusion: 'Acer 更適合 Samsung 的影像呈現：沉浸感的情境照結合 UI，讓讀者看到 AI 出現在自己的一天裡',
    },

    // Apple vs Samsung, copy and image assets only, with which fits Acer better
    benchCompare: {
      copy: [
        { seg: 'Hero', apple: '「全新 Siri AI 亮相。真能幫助你，真的很懂你。」宣言型，角色先登場', samsung: '「Galaxy AI. Make life more seamless.」定義型品牌標語', pick: 'Apple', why: '以角色開場，對應「Acer Qubi 全新亮相!」' },
        { seg: '助理', apple: '「你的 AI 助理，更個人化，更強大。」＋7 則小標，卡上是一句指令', samsung: '「Smart assistance that&#39;s always available」單段說明 Bixby', pick: 'Apple', why: 'Qubi 章用「主標＋一句能說的話」' },
        { seg: '情境功能', apple: '章節小標（視覺智慧／照片與影像…）＋逐條功能句', samsung: '提問式「Can your phone do that?」＋5 分頁 14 則功能標題', pick: 'Samsung', why: '大標＋分頁，一屏看完；Acer 改用肯定句' },
        { seg: '選機', apple: '「體驗 Apple Intelligence 的實力」', samsung: '「Explore our range of Galaxy AI devices」', pick: 'Samsung', why: '直接以裝置類別導購；Acer 改問「哪一台跑得動你的 AI？」' },
        { seg: '相容清單', apple: '「與 Apple Intelligence 相容的裝置」機型後附晶片', samsung: '無此區塊（放在 FAQ）', pick: 'Samsung', why: 'L1 不另設專區，支援機型放進 FAQ 回答' },
        { seg: 'FAQ', apple: '無此區塊（只有註腳）', samsung: '「Frequently Asked Questions」11 題', pick: 'Samsung', why: '集中免責與長尾 SEO' },
      ],
      assets: [
        { seg: 'Hero', apple: 'Image ×6：iPhone 框＋UI 拼貼，白底', samsung: 'Image ×1：手持折疊機 KV，滿版', pick: 'Apple', why: '白底只放一個主角：Qubi 字樣或筆電，搭配 Qubi 3D 動畫' },
        { seg: '助理', apple: 'Image ×7 UI 截圖卡＋精選 Video ×2', samsung: 'Image ×1 Bixby UI 實拍', pick: 'Apple', why: '一句對話配一張畫面；Acer 改以沉浸感的情境照結合 UI呈現' },
        { seg: '情境功能', apple: 'Image ×19 UI 操作介面與精美視覺大圖', samsung: 'Image ×14 沉浸感的情境照結合 UI', pick: 'Samsung', why: '沉浸感的情境照結合 UI，一張圖描述一個沉浸式場景' },
        { seg: '選機', apple: '商品去背 ×15（iPhone・iPad・Mac）', samsung: '商品去背 ×11（手機・平板・手錶・耳機）', pick: '兩者', why: '都用去背商品照；Acer 以系列去背照呈現' },
        { seg: '相容清單', apple: '純文字清單', samsung: '無此區塊', pick: 'Samsung', why: '不另做清單，FAQ 以文字回答' },
        { seg: 'FAQ', apple: '無此區塊', samsung: '純文字手風琴', pick: 'Samsung', why: '不需圖片' },
      ],
    },

    assets: [
      { no: 'A01', name: 'Qubi 3D 角色動畫', seg: 'L1-1', file: 'hero-qubi（即時 3D，或輸出 MP4）', spec: '依影片中 Qubi 造型的 3D 角色；A 版從 Q 探頭→跳出→揮手約 7 秒，B 版從筆電螢幕內探頭揮手約 5 秒；透明底', qty: '1', owner: 'Qubi 團隊／設計', status: '畫面提案已有示意' },
      { no: 'A02', name: '筆電去背圖', seg: 'L1-1', file: 'hero-laptop.png', spec: '筆電正面去背，透明底 PNG @2x（僅 B 版）', qty: '1', owner: 'PM', status: '官網現有', only: 'B 版' },
      { no: 'A03', name: '情境照 1440×960@2x', seg: 'L1-2', file: 'qubi-scene-mail／cutout／meeting.jpg', spec: '情境照，3:2，1440×960 @2x', qty: '3', owner: '設計', status: '示意圖已提供' },
      { no: 'A04', name: '對話腳本', seg: 'L1-2', file: 'qubi-dialogs.xlsx', spec: '3 組對話（誰說、文字、回覆選項）；去背組含裁切框動態', qty: '3 組', owner: 'PM', status: '初稿見畫面提案' },
      { no: 'A05', name: '情境圖 1712×1262@2x', seg: 'L1-3', file: 'scene-<app>.png', spec: '沉浸感的情境照結合 UI，1712×1262 @2x', qty: '7–9', owner: '設計', status: 'v1 可沿用 4 張' },
      { no: 'A06', name: '系列去背照', seg: 'L1-4', file: 'series-<name>.png', spec: '系列去背照，透明底', qty: '約 12', owner: 'PM', status: '官網現有' },
      { no: 'A07', name: 'FAQ 文案', seg: 'L1-5', file: 'faq.docx', spec: 'FAQ 5–8 題＋註腳', qty: '1', owner: 'PM／法務', status: '待提供' },
    ],
  };
})();