/* spec-data.js — shared by deck.config.js and spec.html. Edit spec text here only.
 * Apple / Samsung values：面積比例引用 2026-09-23 拆解；像素值為本版 1920px CSS px、1× 截圖實測（Apple apple-ai.png、Samsung v1 截圖）。
 * Acer L1 values: 本提案建議值。 */
(() => {
  const NONE = { goal: '—', material: '—', ratio: '—', scope: '—', asset: '—', story: '—', none: true };
  window.SPEC = {
    dims: [['goal', '目標'], ['material', '素材'], ['ratio', '比例'], ['scope', '範圍'], ['asset', '資產'], ['story', '敘事']],

    bench: {
      apple: [
        { seg: 'Hero', goal: '立 Siri 為整頁入口', material: '可讀 UI 截圖拼貼（5 張）', ratio: '首屏圖片 29%；UI 字級 ≈13px；標題置中',
          scope: '1 句主標＋限制條件緊貼主標', asset: '中央 iPhone Siri 指令 UI ×1＋周邊介面 ×4', story: '宣言型主標；第一人稱「這是你的螢幕」' },
        { seg: '助理', goal: '讓讀者記住一句能對 Siri 說的話', material: '裝置內 UI 截圖，每張帶一句真實指令；精選卡有影片', ratio: '直式卡 0.83:1（372×450）；圓角 ≈24px；間距 20px；露出第 4 張',
          scope: 'Siri 章輪播 4+ 張，前接精選卡', asset: '每張 = 指令句＋結果截圖', story: '情境小標（Siri AI）＋一句獨立主標' },
        { seg: '情境功能', goal: '用章節標題證明覆蓋面', material: '裝置內 UI 卡', ratio: '同一模板 ×4 章；≈330px／功能',
          scope: '視覺智慧／照片／溝通／生產力，各 3–4+ 張；次要功能降為 4 項 icon', asset: '約 20 張裝置內 UI', story: '每章情境小標＋獨立主標，附「使用可能會有所限制」' },
        { seg: '選機', goal: '依裝置類別選機', material: '去背裝置照', ratio: '4 分頁；主 CTA「進一步了解」，購買為次要文字連結',
          scope: 'iPhone／iPad／筆電／桌機', asset: '每分頁去背照 ×3', story: '「體驗 Apple Intelligence 的實力」' },
        { seg: '相容清單', goal: '用晶片回答「我的裝置能不能用」', material: '純文字清單', ratio: '三欄文字；每列可點',
          scope: '約 30 個機型', asset: '機型＋晶片括號清單', story: '晶片名稱成為選機依據（A18 Pro、M1 以上）' },
        { ...NONE, seg: 'FAQ' },
      ],
      samsung: [
        { seg: 'Hero', goal: '建立 Galaxy AI 品牌印象', material: '棚拍手持商品', ratio: '滿版 1920×1080（1.78:1）；首屏圖片 62%；標題置中',
          scope: '1 句標語＋AI companion 定位', asset: '產品 KV ×1', story: '定義型標語「Make life more seamless」；廣告語氣' },
        { seg: '助理', goal: '把功能收束成單一入口，埋第一個導購 CTA', material: 'Bixby 對話 UI 截圖', ratio: '單段；左文右圖',
          scope: '1 段＋中段 CTA', asset: '對話 UI ×1', story: 'AI companion，人格化定位' },
        { seg: '情境功能', goal: '一屏感受 AI 覆蓋一整天', material: 'UI 合成在生活照', ratio: '橫式卡 1.36:1（856×631）；圓角 ≈24px；間距 94px；圖片占比 35–47%',
          scope: '5 分頁 × 13 功能，預設露出 2 張', asset: '13 張情境照合成 UI', story: '提問式「Can your phone do that?」；第三人稱使用瞬間' },
        { seg: '選機', goal: '依裝置類別選機', material: '去背商品照', ratio: '4 分頁；前接 Try Galaxy 轉場',
          scope: '手機／平板／手錶／耳機', asset: '去背商品攝影', story: '「Explore our range of Galaxy AI devices」＋Learn more' },
        { ...NONE, seg: '相容清單' },
        { seg: 'FAQ', goal: '集中免責與長尾 SEO', material: '文字手風琴', ratio: 'FAQ＋19 條註腳，頁尾前最長的文字段',
          scope: '9–11 題＋19 條註腳', asset: 'FAQ 文案＋註腳', story: '用讀者會問的句子當題目' },
      ],
    },

    l1: [
      { id: 'L1-1', seg: 'Hero：Qubi 亮相', ref: { page: 'apple', region: 'hero', label: 'Apple · Siri Hero' },
        goal: '一眼知道「AIS 是 Acer 的 AI 總稱，Qubi 是你的助理」，並往下讀',
        material: '真實、可讀的 AIS／Qubi UI 截圖拼貼，不用氛圍圖',
        ratio: '首屏圖片 ≤35%；UI 文字 ≥16px（Apple 實測 ≈13px）；主標置中；使用限制緊貼主標下方',
        scope: '1 句主標、1 句副標、1 行限制說明、主 CTA（往下看）＋次 CTA（下載 AIS）',
        asset: '中央 Qubi 對話 UI ×1＋周圍 AIS app UI ×4；繁中實機；PNG 1920 寬',
        story: '提問型標語（沿用 v1 開場）；第一人稱' },
      { id: 'L1-2', seg: 'Qubi 章', ref: { page: 'apple', region: 'siri', label: 'Apple · Siri 章' },
        goal: '讀者記住一句「我可以對 Qubi 說的話」',
        material: 'UI 截圖卡，每張 = 一句指令＋執行結果',
        ratio: '直式卡 0.83:1；圓角 ≈6% 卡寬；一排 3 張、露出第 4 張；約占全頁 15%',
        scope: '4–6 張卡，一組橫向輪播',
        asset: '4–6 組「指令句（繁中）＋結果截圖」，744×900 @2x',
        story: '情境小標（Qubi）＋一句主標，如「你的 AI 助理，更懂你的工作」；指令句即文案' },
      { id: 'L1-3', seg: '情境功能', ref: { page: 'samsung', region: 'scenario', label: 'Samsung · 情境分頁' },
        goal: '一屏感受「AI 覆蓋我一整天」',
        material: '生活照合成 UI，一張圖 = 一個使用時刻',
        ratio: '橫式卡 1.36:1；圓角 ≈3% 卡寬；間距一致；圖片占比 35–47%；≤200px／功能',
        scope: '4 分頁（商務／創意／遊戲／個人化）× 7–9 個 AIS app',
        asset: '每個 app 情境照合成 UI ×1，1712×1262 @2x；v1 圖可沿用或改版',
        story: '提問式大標（「Can your phone do that?」的 Acer 版）；卡片 = 功能標題＋2–3 行說明' },
      { id: 'L1-4', seg: '選機：依裝置類別', ref: { page: 'samsung', region: 'selling', label: 'Samsung · 機種探索' },
        goal: '從「想用的功能」導到 acer.com 裝置分類頁；已有 Acer 電腦 → 下載',
        material: '去背商品照',
        ratio: '4 分頁 × 3 張系列卡；約占全頁 14–17%',
        scope: '筆電／桌機／AIO／掌機；每卡 = 一個系列；主 CTA「進一步了解」→ 分類頁，次 CTA「下載 Acer Intelligence Space」',
        asset: '系列去背照約 12 張（官網現有）＋系列名與一句定位',
        story: '標題承接軟體→硬體：「哪一台跑得動你的 AI？」' },
      { id: 'L1-5', seg: '相容門檻', ref: { page: 'apple', region: 'compat', label: 'Apple · 相容裝置清單' },
        goal: '用硬體門檻回答「我的電腦能不能用」',
        material: '純文字清單，不用圖',
        ratio: '三到四欄文字；每列可點',
        scope: '以系列為單位：可用 AIS app 數、Qubi 等級、硬體門檻（獨顯、RAM）',
        asset: 'v1 相容對照表（output 2）彙整到系列層級',
        story: '仿 Apple 在機型後括號註明晶片，讓硬體名稱成為選機依據' },
      { id: 'L1-6', seg: 'FAQ', ref: { page: 'samsung', region: 'faq', label: 'Samsung · FAQ' },
        goal: '集中處理免責與長尾問題，兼顧 SEO',
        material: '文字手風琴',
        ratio: '單欄；預設收合',
        scope: '5–8 題：支援機型、語言、下載與費用、Qubi 是什麼、資料怎麼處理',
        asset: 'FAQ 文案＋註腳',
        story: '用讀者會問的句子當題目' },
    ],

    overview: [
      { dim: '目標', apple: '介紹整套 AI 系統，最後用相容清單綁回晶片與機型', samsung: '用情境推動硬體探索', acer: '認識 AIS＋Qubi，依裝置類別導到分類頁', from: 'Samsung' },
      { dim: '素材', apple: '可讀 UI 截圖為主（圖片中 92% 為可讀介面）', samsung: '商品照為主，功能用 UI 合成生活照', acer: '可讀 UI（Hero、Qubi）＋生活照合成 UI（情境）＋去背照（選機）', from: 'Apple＋Samsung' },
      { dim: '比例', apple: '首屏圖片 29%；卡片 0.83:1、圓角 ≈24px', samsung: '首屏圖片 62%；卡片 1.36:1、圓角 ≈24px', acer: '首屏圖片 ≤35%；Qubi 卡 0.83:1、情境卡 1.36:1；內容約 5,800px，含導覽與頁尾約 7,000px', from: 'Apple＋Samsung' },
      { dim: '範圍', apple: '6 章約 30 個功能；4 類裝置；約 30 個機型', samsung: '5 分頁 13 個功能；4 類裝置', acer: 'Qubi 4–6 卡；4 分頁 × 7–9 app；4 類裝置 × 3 系列', from: 'Samsung' },
      { dim: '資產', apple: '約 20 張裝置內 UI＋精選影片', samsung: '13 張 UI 合成照＋去背商品照', acer: 'Qubi 指令卡 4–6、情境圖 7–9、系列去背照約 12、相容表 1', from: 'Apple＋Samsung' },
      { dim: '敘事', apple: '角色（Siri）開場；「這是你的螢幕」', samsung: '提問開場；「它出現在你生活的某個時刻」', acer: 'Qubi 開場＋提問式情境＋「哪一台跑得動你的 AI？」', from: 'Apple＋Samsung' },
    ],

    // L1 wireframe, page px at 1440 wide; y is relative to each segment. k: line | block | card | asset | cta | tab.
    // a = asset number (must exist in assets); quiet = draw the box without repeating its chip.
    wireframe: {
      width: 1440,
      segments: [
        { id: 'L1-1', h: 1000, boxes: [
          { k: 'line', x: 420, y: 90, w: 600, h: 44, t: '主標（提問型）' },
          { k: 'line', x: 520, y: 152, w: 400, h: 22 },
          { k: 'line', x: 580, y: 192, w: 280, h: 14, t: '使用限制' },
          { k: 'asset', a: 'A02', x: 140, y: 300, w: 200, h: 260 },
          { k: 'asset', a: 'A02', x: 360, y: 380, w: 200, h: 260, quiet: true },
          { k: 'asset', a: 'A01', x: 600, y: 260, w: 240, h: 480 },
          { k: 'asset', a: 'A02', x: 880, y: 380, w: 200, h: 260, quiet: true },
          { k: 'asset', a: 'A02', x: 1100, y: 300, w: 200, h: 260, quiet: true },
          { k: 'cta', x: 540, y: 820, w: 170, h: 52, t: '往下看', primary: true },
          { k: 'cta', x: 730, y: 820, w: 170, h: 52, t: '下載 AIS' },
        ] },
        { id: 'L1-2', h: 900, boxes: [
          { k: 'line', x: 142, y: 90, w: 140, h: 20, t: 'Qubi' },
          { k: 'line', x: 142, y: 126, w: 620, h: 44, t: '主標' },
          { k: 'asset', a: 'A03', x: 142, y: 250, w: 372, h: 450 },
          { k: 'asset', a: 'A04', x: 166, y: 612, w: 324, h: 64 },
          { k: 'asset', a: 'A03', x: 534, y: 250, w: 372, h: 450, quiet: true },
          { k: 'asset', a: 'A04', x: 558, y: 612, w: 324, h: 64, quiet: true },
          { k: 'asset', a: 'A03', x: 926, y: 250, w: 372, h: 450, quiet: true },
          { k: 'asset', a: 'A04', x: 950, y: 612, w: 324, h: 64, quiet: true },
          { k: 'asset', a: 'A03', x: 1318, y: 250, w: 122, h: 450, quiet: true },
          { k: 'tab', x: 660, y: 740, w: 120, h: 16, t: '' },
        ] },
        { id: 'L1-3', h: 1000, boxes: [
          { k: 'line', x: 420, y: 90, w: 600, h: 44, t: '提問式大標' },
          { k: 'tab', x: 430, y: 180, w: 130, h: 42, t: '商務' },
          { k: 'tab', x: 575, y: 180, w: 130, h: 42, t: '創意' },
          { k: 'tab', x: 720, y: 180, w: 130, h: 42, t: '遊戲' },
          { k: 'tab', x: 865, y: 180, w: 130, h: 42, t: '個人化' },
          { k: 'asset', a: 'A05', x: 142, y: 280, w: 560, h: 412 },
          { k: 'asset', a: 'A05', x: 738, y: 280, w: 560, h: 412, quiet: true },
          { k: 'line', x: 142, y: 724, w: 300, h: 28, t: '功能標題' },
          { k: 'line', x: 142, y: 768, w: 520, h: 14 },
          { k: 'line', x: 142, y: 794, w: 460, h: 14 },
          { k: 'line', x: 738, y: 724, w: 300, h: 28, t: '功能標題' },
          { k: 'line', x: 738, y: 768, w: 520, h: 14 },
          { k: 'line', x: 738, y: 794, w: 460, h: 14 },
        ] },
        { id: 'L1-4', h: 960, boxes: [
          { k: 'line', x: 420, y: 90, w: 600, h: 44, t: '哪一台跑得動你的 AI？' },
          { k: 'tab', x: 430, y: 180, w: 130, h: 42, t: '筆電' },
          { k: 'tab', x: 575, y: 180, w: 130, h: 42, t: '桌機' },
          { k: 'tab', x: 720, y: 180, w: 130, h: 42, t: 'AIO' },
          { k: 'tab', x: 865, y: 180, w: 130, h: 42, t: '掌機' },
          { k: 'card', x: 142, y: 280, w: 370, h: 470 },
          { k: 'card', x: 535, y: 280, w: 370, h: 470 },
          { k: 'card', x: 928, y: 280, w: 370, h: 470 },
          { k: 'asset', a: 'A06', x: 187, y: 310, w: 280, h: 220 },
          { k: 'asset', a: 'A06', x: 580, y: 310, w: 280, h: 220, quiet: true },
          { k: 'asset', a: 'A06', x: 973, y: 310, w: 280, h: 220, quiet: true },
          { k: 'line', x: 172, y: 560, w: 200, h: 26, t: '系列名' },
          { k: 'line', x: 565, y: 560, w: 200, h: 26, t: '系列名' },
          { k: 'line', x: 958, y: 560, w: 200, h: 26, t: '系列名' },
          { k: 'line', x: 172, y: 602, w: 280, h: 14 },
          { k: 'line', x: 565, y: 602, w: 280, h: 14 },
          { k: 'line', x: 958, y: 602, w: 280, h: 14 },
          { k: 'cta', x: 172, y: 670, w: 210, h: 46, t: '進一步了解', primary: true },
          { k: 'cta', x: 565, y: 670, w: 210, h: 46, t: '進一步了解', primary: true },
          { k: 'cta', x: 958, y: 670, w: 210, h: 46, t: '進一步了解', primary: true },
          { k: 'cta', x: 620, y: 820, w: 200, h: 52, t: '下載 AIS' },
        ] },
        { id: 'L1-5', h: 950, boxes: [
          { k: 'line', x: 142, y: 90, w: 520, h: 40, t: '相容門檻標題' },
          { k: 'asset', a: 'A07', x: 142, y: 180, w: 1156, h: 640 },
          { k: 'line', x: 172, y: 250, w: 320, h: 16 },
          { k: 'line', x: 172, y: 290, w: 300, h: 16 },
          { k: 'line', x: 172, y: 330, w: 330, h: 16 },
          { k: 'line', x: 562, y: 250, w: 320, h: 16 },
          { k: 'line', x: 562, y: 290, w: 300, h: 16 },
          { k: 'line', x: 562, y: 330, w: 330, h: 16 },
          { k: 'line', x: 952, y: 250, w: 320, h: 16 },
          { k: 'line', x: 952, y: 290, w: 300, h: 16 },
          { k: 'line', x: 952, y: 330, w: 330, h: 16 },
        ] },
        { id: 'L1-6', h: 950, boxes: [
          { k: 'line', x: 420, y: 90, w: 600, h: 40, t: '常見問題' },
          { k: 'asset', a: 'A08', x: 270, y: 170, w: 900, h: 590 },
          { k: 'block', x: 300, y: 260, w: 840, h: 60, t: '問題 1　＋' },
          { k: 'block', x: 300, y: 340, w: 840, h: 60, t: '問題 2　＋' },
          { k: 'block', x: 300, y: 420, w: 840, h: 60, t: '問題 3　＋' },
          { k: 'block', x: 300, y: 500, w: 840, h: 60, t: '問題 4　＋' },
          { k: 'block', x: 300, y: 580, w: 840, h: 60, t: '問題 5　＋' },
          { k: 'line', x: 270, y: 810, w: 700, h: 12 },
          { k: 'line', x: 270, y: 834, w: 620, h: 12 },
        ] },
      ],
    },

    assets: [
      { no: 'A01', name: 'Qubi 對話 UI', seg: 'L1-1', file: 'hero-qubi-ui.png', spec: 'Qubi 對話 UI，繁中實機，1920 寬', qty: '1', owner: 'Qubi 團隊', status: '待提供' },
      { no: 'A02', name: 'AIS app UI', seg: 'L1-1', file: 'hero-app-ui-01…04.png', spec: 'AIS app UI，繁中實機，文字 ≥16px', qty: '4', owner: 'PM', status: '待提供' },
      { no: 'A03', name: 'Qubi 卡 744×900@2x', seg: 'L1-2', file: 'qubi-card-01…06.png', spec: '指令句＋結果截圖，744×900 @2x', qty: '4–6', owner: 'Qubi 團隊', status: '待提供' },
      { no: 'A04', name: '指令句', seg: 'L1-2', file: 'qubi-prompts.xlsx', spec: '每張卡的指令句（繁中）', qty: '4–6 句', owner: 'PM', status: '待提供' },
      { no: 'A05', name: '情境圖 1712×1262@2x', seg: 'L1-3', file: 'scene-<app>.png', spec: '生活照合成 UI，1712×1262 @2x', qty: '7–9', owner: '設計', status: 'v1 可沿用 4 張' },
      { no: 'A06', name: '系列去背照', seg: 'L1-4', file: 'series-<name>.png', spec: '系列去背照，透明底', qty: '約 12', owner: 'PM', status: '官網現有' },
      { no: 'A07', name: '相容表', seg: 'L1-5', file: 'compat-series.csv', spec: '系列 × 可用 app 數 × Qubi 等級 × 硬體門檻', qty: '1', owner: 'PM', status: '由 v1 對照表彙整' },
      { no: 'A08', name: 'FAQ 文案', seg: 'L1-6', file: 'faq.docx', spec: 'FAQ 5–8 題＋註腳', qty: '1', owner: 'PM／法務', status: '待提供' },
    ],
  };
})();